### ISSUE TITLE
[Infra][Documentation] Kubernetes Operator - Document infrastructure/tooling to deploy new LocalNet node

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-operator#10]
# Objective
Document and expose the required tooling, infrastructure and configurations to deploy additional LocalNet nodes using the pocket-operator.

# Origin Document

Several demo flows are outlined in https://github.com/pokt-network/pocket/issues/349 on how we can test peer discovery and state sync, both of which are blocked by being able to deploy additional local operators.

Note that this is simply documentation-only follow-up work to #7.

# Goals / Deliverables 
- [x] Update [pocket-operator readme](https://github.com/pokt-network/pocket-operator/blob/master/README.md) as needed
- [x] Update LocalNet documentation in the [pocket development guide](https://github.com/pokt-network/pocket/tree/main/docs/development) on how a new local node can be spun up

---

Creators: @jessicadaugherty @Olshansk

**Comment by okdas** [comment]
Focusing on this today/tomorrow

**Comment by okdas** [comment]
Since we pivoted to run LocalNet without operator (for now), I did add an ability to scale validators in scope of https://github.com/pokt-network/pocket/pull/354. 

operator part is covered in scope of https://github.com/pokt-network/pocket-operator/pull/12, along with other changes necessary to stabilize operator local development, and to support lates configuration changes for validators.

**Comment by okdas** [comment]
Marking this as "in review" until https://github.com/pokt-network/pocket/pull/354 is reviewed - because that is where the tooling and documentation is at.

**Comment by okdas** [comment]
With https://github.com/pokt-network/pocket/pull/354 reviewed and merged, so is this ticket.
