### ISSUE TITLE
Client container not working properly

### ISSUE THREAD

**Issue by lander2k2** [pokt-network/pocket-operator#2]
**Describe the bug**
When running the pocket client, none of the prompted menu items work.  Each just hang and fail to return a response.

**To Reproduce**
1. Run through the "Local Development & Testing" instructions in the README
2. After running the dev client, select any of the menu items

**Expected behavior**
The dev client should respond with info appropriate to the selection.  It returns nothing.

**Additional context**
Looking at the [docker-compose config](https://github.com/pokt-network/pocket/blob/main/build/deployments/docker-compose.yaml) in the pocket repo, it looks as though there are missing dependencies for the client.  I'm unsure if we want to support those components in the operator or figure out another way to set up tests for validators created with this operator.

**Comment by okdas** [comment]
@lander2k2 the reason this `client` CLI currently exists is because v1 RPC and CLI interface has not been implemented yet. There is an ongoing effort to implement it, and we no longer will need the `client` cli once this ticket is done - https://github.com/pokt-network/pocket/issues/112.

Since all `client` does is sends protobuf messages, I suspect there might be connectivity issues or it is unable to reach the nodes? I'm trying to replicate this now with operator.

**Comment by okdas** [comment]
Addressed in #6 - I was only planning on changing the config files, but ended up also changing imports from your repo to the new one which naturally triggered a lot of code generated changes.

It is possible to run the client now, the kubectl command example in readme changed though - we will make this prettier later. It might crash due to inability to talk to node sometimes - I didn't spend much time investigating why - it might not even be replicated on setup from scratch.
